#!/bin/bash

git stash -q --keep-index

echo "Running git pre-commit hook"

./gradlew check
echo "Running android lint"
./gradlew lint

echo "Writing to SonarQube"
./gradlew sonarqube  -Dsonar.host.url=http://localhost:9000/

RESULT=$?

git stash pop -q

# return 1 exit code if running checks fails
[ $RESULT -ne 0 ] && exit 1
exit 0